name: GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */3 * * *

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm i
      
      - run: npm run update

      - run: npm run build
        env:
          BASE_PATH: /SimpleCovid19ChartInJapan
      
      - name: Save Data
        run: cp -r ./data/ ./out/data/

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
